FROM python:3.11-slim

COPY storage_node.py /storage_node.py
COPY utils.py /utils.py
COPY init_ftp_storage.py /init_ftp_storage.py

WORKDIR /app

VOLUME /data

EXPOSE 50

CMD ["python", "../init_ftp_storage.py"]